/* Atlas calendar: shared event data, no game-engine mutations. Inlined by build. */
(() => {
 'use strict';
 const P=window.__pgo,U=window.AtlasEventUI,host=document.querySelector('#eventsCard');
 if(!P||!U||!host)return;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const parse=s=>{if(!s)return null;const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(s)?s+'T00:00':s);return isNaN(+d)?null:d};
 const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
 const midnight=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
 const finish=e=>{const d=parse(e[4]);return d&&/^\d{4}-\d{2}-\d{2}$/.test(e[4])?add(d,1):d};
 const monday=d=>add(midnight(d),-((d.getDay()+6)%7));
 const overlap=(e,a,b)=>{const s=parse(e[3]),t=finish(e);return !!(s&&t&&t>s&&s<b&&t>a)};
 const multi=e=>{const a=parse(e[3]),b=finish(e);return !!(a&&b&&key(a)!==key(new Date(+b-1)))};
 const kind=e=>/^max-/.test(e[1])?'max':/raid/.test(e[1])?'raid':/research|timed|choose-your-path/.test(e[1])?'research':'catch';
 const categories={all:'Vše',raid:'Raidy',max:'Max',catch:'Chytání',research:'Výzkum'};
 const symbol={raid:'◈',max:'✦',catch:'◉',research:'◇'};
 const title=e=>e[1]==='raid-hour'?'Raidová hodina':/spotlight/.test(e[1])?'Hodina Pokémonů':/community-day/.test(e[1])?'Community Day':String(e[0]).replace(/ in (?:5-star Raid Battles|Mega Raids|Shadow Raids)$/i,'').replace(/ during Max Monday$/i,' · Max pondělí').replace(/ Raid Hour$/i,' · Raidová hodina').replace(/ Spotlight Hour$/i,' · Hodina Pokémonů');
 const time=e=>{if(!/T/.test(e[3])||!/T/.test(e[4]))return 'Čas nebyl potvrzen';const a=parse(e[3]),b=finish(e);if(!a||!b)return 'Termín nepotvrzen';const f=d=>d.toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'});return multi(e)?`${U.format(e[3])} – ${U.format(e[4])}`:`${f(a)}–${f(b)}`};
 const fullDate=d=>d.toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'long'});
 const data=()=>P.eventsData()||{};
 const all=()=>data().events||[];
 const dated=()=>all().filter(e=>parse(e[3])&&finish(e)&&finish(e)>parse(e[3]));
 let selected=midnight(new Date()),anchor=monday(selected),mode='week',filter='all',selectedIndex=null,expandedDay=null,homeDay=null,allSpans=false;
 const root=document.createElement('div');root.id='atlasCalendar';host.append(root);host.classList.add('atlas-calendar-host');
 const matches=e=>filter==='all'||kind(e)===filter;
 const eventsFor=d=>dated().filter(e=>matches(e)&&overlap(e,d,add(d,1))).sort((a,b)=>+parse(a[3])-+parse(b[3]));
 const eventId=e=>all().indexOf(e);
 function art(e){return `<span class="ac-art" data-kind="${kind(e)}">${U.names(e).slice(0,2).map(U.image).join('')}</span>`}
 function tile(e,compact=false){const i=eventId(e);return `<button class="ac-event ${compact?'ac-event-small':''}" title="${esc(e[0])}" data-ac-event="${i}" data-kind="${kind(e)}" aria-pressed="${selectedIndex===i}">${art(e)}<span class="ac-event-text"><span class="ac-tile-kind" aria-hidden="true">${symbol[kind(e)]}</span><b>${esc(title(e))}</b><small>${esc(time(e))}</small></span></button>`}
 function dayButton(d){return `<button class="ac-day" data-ac-day="${key(d)}" aria-pressed="${key(d)===key(selected)}" ${key(d)===key(new Date())?'aria-current="date"':''}><span>${d.toLocaleDateString('cs-CZ',{weekday:'short'})}</span><b>${d.getDate()}.</b><small>${d.toLocaleDateString('cs-CZ',{month:'short'})}</small></button>`}
 function agenda(d){const es=eventsFor(d),short=es.filter(e=>!multi(e)),long=es.filter(multi);return `<section class="ac-agenda-day"><h3>${key(d)===key(new Date())?'Dnes · ':key(d)===key(add(new Date(),1))?'Zítra · ':''}${esc(fullDate(d))}</h3>${short.map(e=>tile(e)).join('')||'<p class="ac-empty">Žádná potvrzená krátká akce.</p>'}${long.length?`<details class="ac-also"><summary>Probíhá také · ${long.length}</summary>${long.map(e=>tile(e,true)).join('')}</details>`:''}</section>`}
 function week(){const ds=Array.from({length:7},(_,i)=>add(anchor,i)),es=dated().filter(e=>matches(e)&&overlap(e,anchor,add(anchor,7)));return `<div class="ac-week"><div class="ac-days">${ds.map(dayButton).join('')}</div><div class="ac-section-label">Vícedenní akce</div><div class="ac-spans">${es.filter(multi).slice(0,allSpans?undefined:3).map((e,row)=>{const visible=ds.map((d,i)=>overlap(e,d,add(d,1))?i:-1).filter(i=>i>=0);return `<button class="ac-span" data-kind="${kind(e)}" data-ac-event="${eventId(e)}" style="grid-column:${visible[0]+1}/${visible[visible.length-1]+2};grid-row:${row+1}" title="${esc(e[0])}"><span>${symbol[kind(e)]}</span> ${esc(title(e))}<span aria-hidden="true">→</span></button>`}).join('')||'<p class="ac-empty">Bez vícedenní akce.</p>'}</div>${es.filter(multi).length>3?`<button class="ac-expand-spans" data-ac-spans>${allSpans?'Sbalit vícedenní akce':'Další vícedenní akce · '+(es.filter(multi).length-3)} <span>${allSpans?'−':'+'}</span></button>`:''}<div class="ac-section-label">Akce v konkrétní čas</div><div class="ac-columns">${ds.map(d=>{const items=es.filter(e=>!multi(e)&&overlap(e,d,add(d,1))),show=expandedDay===key(d)?items:items.slice(0,3);return `<section class="ac-column" aria-label="${esc(fullDate(d))}">${show.map(e=>tile(e,true)).join('')||'<span class="ac-no-event">—</span>'}${items.length>3&&expandedDay!==key(d)?`<button class="ac-more" data-ac-expand="${key(d)}">Další ${items.length-3}</button>`:''}</section>`}).join('')}</div></div>`}
 function month(){const start=new Date(anchor.getFullYear(),anchor.getMonth(),1),first=monday(start);return `<div class="ac-month-labels">${['po','út','st','čt','pá','so','ne'].map(x=>`<span>${x}</span>`).join('')}</div><div class="ac-month">${Array.from({length:42},(_,i)=>{const d=add(first,i),es=eventsFor(d);return `<section class="ac-month-day ${d.getMonth()!==start.getMonth()?'ac-outside':''}">${dayButton(d)}${es.slice(0,2).map(e=>`<button class="ac-month-event" data-kind="${kind(e)}" data-ac-event="${eventId(e)}">${esc(title(e))}</button>`).join('')}${es.length>2?`<button class="ac-more" data-ac-show-day="${key(d)}">+${es.length-2} další</button>`:''}</section>`}).join('')}</div>`}
 function side(){const e=all()[selectedIndex];return `<aside class="ac-detail" aria-label="Detail události"><div class="ac-detail-heading"><h2>${esc(fullDate(selected))}</h2>${e?'<button data-ac-close aria-label="Zavřít náhled události">×</button>':''}</div>${e?`${art(e)}<span class="ac-category" data-kind="${kind(e)}">${symbol[kind(e)]} ${categories[kind(e)]}</span><h3>${esc(title(e))}</h3>${U.names(e).length?`<p class="ac-detail-species">${esc(U.names(e).join(' · '))}</p>`:''}<p class="ac-detail-time">◷ ${esc(time(e))}</p><p>${['raid','max'].includes(kind(e))?'Otevři přehled bossů a připrav tým.':'Prohlédni si dostupné Pokémony, bonusy a podmínky akce.'}</p><button class="ac-primary" ${['raid','max'].includes(kind(e))?'data-ac-teams':`data-ac-full="${selectedIndex}"`}>${['raid','max'].includes(kind(e))?'Připravit tým':'Prohlédnout událost'} →</button><button class="ac-text-link" data-ac-full="${selectedIndex}">Detail události →</button>`:`<p>Vyber událost v kalendáři.</p>${eventsFor(selected).map(e=>tile(e,true)).join('')}`}</aside>`}
 function render(){root.dataset.mode=mode;const stamp=data()._meta?.stazeno||P.dataInfo?.events,stale=!parse(stamp)||Date.now()-parse(stamp)>172800000,unknown=all().filter(e=>!parse(e[3])||!finish(e)||finish(e)<=parse(e[3]));const range=mode==='month'?anchor.toLocaleDateString('cs-CZ',{month:'long',year:'numeric'}):`${anchor.getDate()}.–${add(anchor,6).toLocaleDateString('cs-CZ',{day:'numeric',month:'long',year:'numeric'})}`;
 root.innerHTML=`<div class="ac-layout"><div class="ac-content"><div class="ac-toolbar"><h2>Kalendář událostí</h2><div class="ac-controls"><button data-ac-today>Dnes</button><button data-ac-shift="-1" aria-label="Předchozí období">‹</button><button data-ac-shift="1" aria-label="Další období">›</button><b>${esc(range)}</b><div class="ac-views" aria-label="Zobrazení kalendáře">${[['week','Týden'],['month','Měsíc'],['list','Seznam']].map(([k,v])=>`<button data-ac-mode="${k}" aria-pressed="${mode===k}">${v}</button>`).join('')}</div></div></div><div class="ac-filters" aria-label="Kategorie událostí">${Object.entries(categories).map(([k,v])=>`<button data-ac-filter="${k}" data-kind="${k}" aria-pressed="${filter===k}">${k==='all'?'':'<span class="ac-dot"></span>'}${v}</button>`).join('')}</div><div class="ac-desktop-view">${mode==='week'?week():mode==='month'?month():Array.from({length:7},(_,i)=>agenda(add(anchor,i))).join('')}</div><div class="ac-mobile-view"><div class="ac-days">${Array.from({length:7},(_,i)=>dayButton(add(anchor,i))).join('')}</div>${agenda(selected)}${agenda(add(selected,1))}</div></div>${side()}</div>${unknown.length?`<details class="ac-unconfirmed"><summary>Termín nepotvrzen · ${unknown.length}</summary>${unknown.filter(matches).map(e=>tile(e,true)).join('')}</details>`:''}<p class="ac-source">Data: ${esc(stamp||'datum neznámé')}${stale?' · Aktualitu ověř ve zdroji.':''} · Časy podle údajů zdroje${Intl.DateTimeFormat().resolvedOptions().timeZone?' · '+esc(Intl.DateTimeFormat().resolvedOptions().timeZone):''}</p>`;
 }
 function selectDefault(){const es=eventsFor(selected);selectedIndex=eventId(es.find(e=>!multi(e))||es[0]);if(selectedIndex<0)selectedIndex=null}
 function chooseDay(d){selected=midnight(d);selectDefault();expandedDay=key(d);render()}
 root.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;const y=window.scrollY;
 if(b.hasAttribute('data-ac-event')){selectedIndex=Number(b.dataset.acEvent);const start=parse(all()[selectedIndex]?.[3]);if(start&&!overlap(all()[selectedIndex],selected,add(selected,1)))selected=midnight(start);render();if(innerWidth<1100)U.open(selectedIndex)}
 else if(b.dataset.acFull!==undefined)U.open(Number(b.dataset.acFull));
 else if(b.hasAttribute('data-ac-teams'))window.__atlasTest.go('teams','cheatCard');
 else if(b.hasAttribute('data-ac-close')){selectedIndex=null;render()}
 else if(b.dataset.acDay)chooseDay(parse(b.dataset.acDay));
 else if(b.dataset.acShowDay){mode='list';anchor=monday(parse(b.dataset.acShowDay));chooseDay(parse(b.dataset.acShowDay))}
 else if(b.dataset.acExpand){expandedDay=b.dataset.acExpand;render()}
 else if(b.dataset.acFilter){filter=b.dataset.acFilter;selectDefault();render()}
 else if(b.dataset.acMode){mode=b.dataset.acMode;anchor=mode==='month'?new Date(selected.getFullYear(),selected.getMonth(),1):monday(selected);render()}
 else if(b.hasAttribute('data-ac-spans')){allSpans=!allSpans;render()}
 else if(b.hasAttribute('data-ac-today')){selected=midnight(new Date());anchor=mode==='month'?new Date(selected.getFullYear(),selected.getMonth(),1):monday(selected);selectDefault();render()}
 else if(b.dataset.acShift){const n=Number(b.dataset.acShift);anchor=mode==='month'?new Date(anchor.getFullYear(),anchor.getMonth()+n,1):add(anchor,7*n);selected=new Date(anchor);selectDefault();render()}
 if(!b.hasAttribute('data-ac-teams')){window.scrollTo({top:y,behavior:'instant'});const attr=['data-ac-mode','data-ac-filter','data-ac-day','data-ac-shift','data-ac-today','data-ac-expand','data-ac-close'].find(a=>b.hasAttribute(a));if(attr){const val=b.getAttribute(attr);root.querySelector(`[${attr}="${val}"]`)?.focus({preventScroll:true})}}
 });
 function featured(){const now=new Date(),future=add(now,14),es=dated().filter(e=>e[1]!=='season'&&e[1]!=='raid-battles'&&finish(e)>now&&parse(e[3])<future),used=new Set(),out=[];const take=e=>{if(e&&!used.has(e)){used.add(e);out.push(e)}};take(es.filter(e=>!multi(e)).sort((a,b)=>+parse(a[3])-+parse(b[3]))[0]);take(es.filter(e=>parse(e[3])<=now).sort((a,b)=>+finish(a)-+finish(b))[0]);take(es.filter(e=>parse(e[3])>now&&!used.has(e)).sort((a,b)=>+parse(a[3])-+parse(b[3]))[0]);es.sort((a,b)=>+finish(a)-+finish(b)).forEach(e=>{if(out.length<3)take(e)});return out}
 function decorateHome(){const home=document.querySelector('#atlasHome'),panel=home.querySelector('.atlas-overview-calendar');if(!panel)return;const grid=panel.querySelector('.atlas-event-grid');grid.innerHTML=featured().map(e=>U.card(e).replace(/<h3>[\s\S]*?<\/h3>/,`<h3>${esc(title(e))}</h3>`)).join('')||'<p class="ac-empty">Nemáme potvrzené nadcházející události.</p>';grid.querySelectorAll('.atlas-event-card').forEach(card=>{const status=card.querySelector('.atlas-event-status'),copy=card.querySelector('.atlas-event-copy');if(status&&copy)copy.prepend(status)});panel.querySelector('.atlas-panel-head').innerHTML='<h2>Dnes a brzy</h2><button class="ac-text-link" data-ac-open-calendar>Celý kalendář →</button>';const week=panel.querySelector('.atlas-week');week.innerHTML=Array.from({length:7},(_,i)=>{const d=add(monday(new Date()),i);return `<button data-ac-home-day="${key(d)}" aria-pressed="${(homeDay||key(new Date()))===key(d)}"><span>${d.toLocaleDateString('cs-CZ',{weekday:'short'})}</span><b>${d.getDate()}.</b><small>${dated().filter(e=>overlap(e,d,add(d,1))).length?'●':'·'}</small></button>`}).join('');if(!panel.querySelector('.ac-home-week-label'))week.insertAdjacentHTML('beforebegin','<h3 class="ac-home-week-label">Tento týden</h3>');panel.querySelectorAll(':scope > .atlas-small-note,:scope > .atlas-mini-btn').forEach(e=>e.remove());let program=panel.querySelector('.ac-home-program');if(!program){program=document.createElement('div');program.className='ac-home-program';panel.append(program)}program.innerHTML=homeDay?`<h3>${esc(fullDate(parse(homeDay)))}</h3>${dated().filter(e=>overlap(e,parse(homeDay),add(parse(homeDay),1))).map(e=>`<button data-event-index="${eventId(e)}"><b>${esc(title(e))}</b><span>${esc(time(e))}</span></button>`).join('')||'<p>Bez potvrzené akce.</p>'}`:'';}
 window.AtlasDecorateHome=decorateHome;
 document.querySelector('#atlasHome').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.acHomeDay){homeDay=homeDay===b.dataset.acHomeDay?null:b.dataset.acHomeDay;decorateHome();document.querySelector(`[data-ac-home-day="${b.dataset.acHomeDay}"]`)?.focus({preventScroll:true})}if(b.hasAttribute('data-ac-open-calendar')){if(homeDay){selected=parse(homeDay);anchor=mode==='month'?new Date(selected.getFullYear(),selected.getMonth(),1):monday(selected)}selectDefault();render();window.__atlasTest.go('events','eventsCard')}});
 window.addEventListener('atlas:route',e=>{if(e.detail==='eventsCard'){host.open=true;render()}});
 window.AtlasCalendar={render,getState:()=>({mode,filter,selected:key(selected),anchor:key(anchor)}),featured,overlap,multi};
 selectDefault();render();decorateHome();
})();
